name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install linters and security tools
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.57.1

      - name: Lint
        run: $(go env GOPATH)/bin/golangci-lint run ./...

      - name: Run Unit Tests
        run: go test ./... -v

      - name: Static Code Analysis (gosec)
        continue-on-error: true
        run: $(go env GOPATH)/bin/gosec ./...

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:${{ github.sha }} .

      - name: Scan Docker Image (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/${{ github.repository }}:${{ github.sha }}
          format: 'table'
          severity: 'CRITICAL,HIGH'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REPO_PAT }}

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ github.sha }}

  cd:
    name: GitOps Trigger
    needs: ci
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Manifest Repo
        uses: actions/checkout@v4
        with:
          repository: dummy-roro/shorten-url-manifests
          token: ${{ secrets.REPO_PAT }}
          path: mainfests

      - name: Update Image Tag in Manifest
        run: |
          sed -i "s|image:.*|image: ghcr.io/${{ github.repository }}:${{ github.sha }}|" mainfests/deployment.yaml

      - name: Commit and Push Changes
        run: |
          cd gitops
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -am "Update image to ${{ github.sha }}"
          git push
